'use strict';

/**
 * sync-web.js
 *
 * Generates web/src/data/flats.ts entirely from the API/DB.
 * Replaces the legacy sync-availability.js (which only synced availability
 * to a JSON overlay).
 *
 * Output is the canonical flats.ts: typed, fully populated with multilingual
 * content, photos (active, sorted by is_cover then sort_order), reviews,
 * coordinates and per-flat amenities — exactly what the Astro build needs.
 *
 * Usage: node scripts/sync-web.js [--api http://localhost:3000]
 */

const fs = require('fs');
const path = require('path');

const API_BASE = process.argv.includes('--api')
  ? process.argv[process.argv.indexOf('--api') + 1]
  : 'http://localhost:3000';

const REPO_ROOT = path.resolve(__dirname, '..');
const OUT_PATH = path.join(REPO_ROOT, 'web', 'src', 'data', 'flats.ts');
const IMG_PREFIX = '/casas-vigo/images';

const LANGS = ['es', 'en', 'gl', 'fr', 'de', 'ko', 'pt', 'pl'];

// ─── HTTP ─────────────────────────────────────────────────────

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → ${res.status}`);
  return res.json();
}

// ─── TS code generation ───────────────────────────────────────

function tsString(s) {
  return JSON.stringify(s ?? '');
}

function tsI18n(obj) {
  if (!obj) return '{}';
  // Stable order matching translations.ts
  const parts = LANGS
    .filter(l => obj[l] !== undefined)
    .map(l => `${l}: ${tsString(obj[l])}`);
  return `{ ${parts.join(', ')} }`;
}

function tsArray(arr, indent = '      ') {
  if (!arr || !arr.length) return '[]';
  return '[\n' + arr.map(s => `${indent}${tsString(s)}`).join(',\n') + `\n${indent.slice(2)}]`;
}

function parseJsonField(v, fallback) {
  if (!v) return fallback;
  if (typeof v === 'object') return v;
  try { return JSON.parse(v); } catch { return fallback; }
}

// ─── Build TS file ────────────────────────────────────────────

async function main() {
  const [flatsRes, roomsRes, photosRes, reviewsRes] = await Promise.all([
    fetchJson(`${API_BASE}/api/flats`),
    fetchJson(`${API_BASE}/api/rooms`),
    fetchJson(`${API_BASE}/api/photos`),
    fetchJson(`${API_BASE}/api/reviews`),
  ]);

  const flats = flatsRes.data;
  const rooms = roomsRes.data;
  const photos = photosRes.data;
  const reviews = reviewsRes.data;

  // Group photos by flat_id and (flat_id, room_id)
  const flatPhotos = new Map();   // flat_id → photos[] (room_id IS NULL, active)
  const roomPhotos = new Map();   // room_id → photos[] (active)
  for (const p of photos) {
    if (!p.active) continue;
    if (p.room_id) {
      if (!roomPhotos.has(p.room_id)) roomPhotos.set(p.room_id, []);
      roomPhotos.get(p.room_id).push(p);
    } else {
      if (!flatPhotos.has(p.flat_id)) flatPhotos.set(p.flat_id, []);
      flatPhotos.get(p.flat_id).push(p);
    }
  }
  // Sort: covers first, then by sort_order
  const photoSort = (a, b) => {
    if ((b.is_cover ? 1 : 0) !== (a.is_cover ? 1 : 0)) return (b.is_cover ? 1 : 0) - (a.is_cover ? 1 : 0);
    return (a.sort_order ?? 0) - (b.sort_order ?? 0);
  };
  for (const arr of flatPhotos.values()) arr.sort(photoSort);
  for (const arr of roomPhotos.values()) arr.sort(photoSort);

  // Group rooms by flat_id (preserve API order)
  const roomsByFlat = new Map();
  for (const r of rooms) {
    if (!roomsByFlat.has(r.flat_id)) roomsByFlat.set(r.flat_id, []);
    roomsByFlat.get(r.flat_id).push(r);
  }

  // Group reviews by flat_id (already ordered by sort_order from API)
  const reviewsByFlat = new Map();
  for (const r of reviews) {
    if (!reviewsByFlat.has(r.flat_id)) reviewsByFlat.set(r.flat_id, []);
    reviewsByFlat.get(r.flat_id).push(r);
  }

  // Build TS source
  const out = [];
  out.push(`// AUTO-GENERATED by scripts/sync-web.js — DO NOT EDIT BY HAND`);
  out.push(`// Source of truth: SQLite (data/casasvigo.db) + photos + reviews`);
  out.push(`// To update: edit via dashboard, then run preview-web.js → publish`);
  out.push(``);
  out.push(`import availabilityData from './availability.json';`);
  out.push(`import type { I18nText } from '../i18n/translations';`);
  out.push(``);
  out.push(`export interface Review {`);
  out.push(`  name: string;`);
  out.push(`  text: I18nText;`);
  out.push(`}`);
  out.push(``);
  out.push(`export interface Room {`);
  out.push(`  id: string;`);
  out.push(`  name: I18nText;`);
  out.push(`  price: number;`);
  out.push(`  available: boolean;`);
  out.push(`  available_from?: string | null;`);
  out.push(`  size: string;`);
  out.push(`  features: string[];`);
  out.push(`  images: string[];`);
  out.push(`}`);
  out.push(``);
  out.push(`export interface Flat {`);
  out.push(`  slug: string;`);
  out.push(`  name: I18nText;`);
  out.push(`  address: string;`);
  out.push(`  neighborhood: I18nText;`);
  out.push(`  description: I18nText;`);
  out.push(`  image: string;`);
  out.push(`  images: string[];`);
  out.push(`  rooms: Room[];`);
  out.push(`  amenities: string[];`);
  out.push(`  coordinates: { lat: number; lng: number };`);
  out.push(`  reviews: Review[];`);
  out.push(`  /** If set, the flat is rented as a whole at this monthly price (rooms are not rented individually). */`);
  out.push(`  wholeFlatPrice?: number;`);
  out.push(`}`);
  out.push(``);
  out.push(`const IMG = ${tsString(IMG_PREFIX)};`);
  out.push(``);
  out.push(`export const flats: Flat[] = [`);

  for (const flat of flats) {
    if (!flat.web_slug) {
      console.warn(`  WARN: flat slug=${flat.slug} has no web_slug — skipping`);
      continue;
    }
    const nameI18n = parseJsonField(flat.name_i18n, {});
    const neighI18n = parseJsonField(flat.neighborhood_i18n, {});
    const descI18n = parseJsonField(flat.description_i18n, {});
    const coords = parseJsonField(flat.coordinates, { lat: 0, lng: 0 });
    const amenities = parseJsonField(flat.amenities, []);
    const flatRooms = roomsByFlat.get(flat.id) || [];
    const flatPhotoList = flatPhotos.get(flat.id) || [];
    const flatReviewList = reviewsByFlat.get(flat.id) || [];

    const imageList = flatPhotoList.map(p => `\`\${IMG}/${p.filename}\``);
    const cover = imageList[0] || `''`;

    out.push(`  {`);
    out.push(`    slug: ${tsString(flat.web_slug)},`);
    if (flat.whole_flat_price != null) {
      out.push(`    wholeFlatPrice: ${flat.whole_flat_price},`);
    }
    out.push(`    name: ${tsI18n(nameI18n)},`);
    out.push(`    address: ${tsString(flat.address)},`);
    out.push(`    neighborhood: ${tsI18n(neighI18n)},`);
    out.push(`    description: ${tsI18n(descI18n)},`);
    out.push(`    image: ${cover},`);
    out.push(`    images: ${imageList.length ? '[\n      ' + imageList.join(',\n      ') + '\n    ]' : '[]'},`);
    out.push(`    rooms: [`);

    for (const room of flatRooms) {
      const roomNameI18n = parseJsonField(room.name_i18n, {});
      const features = parseJsonField(room.features, []);
      const ph = (roomPhotos.get(room.id) || []).map(p => `\`\${IMG}/${p.filename}\``);
      const webId = room.web_id || `${flat.web_id_prefix || flat.slug}-${room.slug}`;

      out.push(`      {`);
      out.push(`        id: ${tsString(webId)},`);
      out.push(`        name: ${tsI18n(roomNameI18n)},`);
      out.push(`        price: ${room.price_monthly}, available: ${!!room.available}, size: ${tsString(room.size_m2 ? `${room.size_m2}m²` : '')},`);
      out.push(`        features: ${features.length ? '[' + features.map(tsString).join(', ') + ']' : '[]'},`);
      out.push(`        images: ${ph.length ? '[\n          ' + ph.join(',\n          ') + '\n        ]' : '[]'},`);
      out.push(`      },`);
    }

    out.push(`    ],`);
    out.push(`    amenities: ${amenities.length ? '[' + amenities.map(tsString).join(', ') + ']' : '[]'},`);
    out.push(`    coordinates: { lat: ${coords.lat}, lng: ${coords.lng} },`);
    out.push(`    reviews: [`);

    for (const r of flatReviewList) {
      const text = parseJsonField(r.text_i18n, {});
      out.push(`      { name: ${tsString(r.reviewer_name)}, text: ${tsI18n(text)} },`);
    }

    out.push(`    ],`);
    out.push(`  },`);
  }

  out.push(`];`);
  out.push(``);
  out.push(`/** Days threshold for "available soon" badges (used by FlatCard + RoomCard) */`);
  out.push(`export const SOON_DAYS = 30;`);
  out.push(``);
  out.push(`/** Sort rooms: available first, then by nearest available_from, then occupied without date */`);
  out.push(`export function sortRoomsByAvailability(rooms: Room[]): Room[] {`);
  out.push(`  return [...rooms].sort((a, b) => {`);
  out.push(`    if (a.available && !b.available) return -1;`);
  out.push(`    if (!a.available && b.available) return 1;`);
  out.push(`    if (!a.available && !b.available) {`);
  out.push(`      if (a.available_from && b.available_from) {`);
  out.push(`        return new Date(a.available_from).getTime() - new Date(b.available_from).getTime();`);
  out.push(`      }`);
  out.push(`      if (a.available_from) return -1;`);
  out.push(`      if (b.available_from) return 1;`);
  out.push(`    }`);
  out.push(`    return 0;`);
  out.push(`  });`);
  out.push(`}`);
  out.push(``);
  out.push(`// Apply availability overlay from API (auto-generated by scripts/sync-availability.js)`);
  out.push(`const avail = (availabilityData as { rooms: Record<string, { available: boolean; price: number; available_from: string | null }> }).rooms;`);
  out.push(`for (const flat of flats) {`);
  out.push(`  for (const room of flat.rooms) {`);
  out.push(`    const data = avail[room.id];`);
  out.push(`    if (data) {`);
  out.push(`      room.available = data.available;`);
  out.push(`      room.price = data.price;`);
  out.push(`      room.available_from = data.available_from ?? null;`);
  out.push(`    } else {`);
  out.push(`      room.available_from = null;`);
  out.push(`    }`);
  out.push(`  }`);
  out.push(`}`);
  out.push(``);

  fs.writeFileSync(OUT_PATH, out.join('\n'));
  console.log(`sync-web: wrote ${flats.length} flats / ${rooms.length} rooms / ${photos.filter(p => p.active).length} photos / ${reviews.length} reviews → ${OUT_PATH}`);
}

main().catch(err => {
  console.error('sync-web failed:', err.message);
  process.exit(1);
});
